name: platformchannels
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  local_auth: ^2.2.0
  local_auth_android: ^1.0.0
  local_auth_darwin: ^1.2.1
  easy_permission_validator: ^4.0.0
  flutter_animate: ^4.5.0
  pattern_lock: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  url_launcher: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Iransans
      fonts:
        - asset: assets/fonts/1.ttf